### ISSUE TITLE
License

### ISSUE THREAD

**Issue by themperek** [xantorohara/led-matrix-editor#1]
I would like to reuse your project.
Could you provide license information for it?

**Comment by xantorohara** [comment]
Free to reuse. MIT license is ok?

**Comment by themperek** [comment]
MIT is OK.
Anything is OK. Just no license is bad.

**Comment by xantorohara** [comment]
Added LICENSE file

**Comment by themperek** [comment]
:+1: 
Thank you.

**Comment by themperek** [comment]
FYI
Some initial version: https://github.com/themperek/micropython-lme-server
